export const vacancies = [
  {
    id: "sniper",
    title: "Снайпер",
    unitId: "sniper_unit",
    unit: "Снайперська група",
    short: "Бойова робота в штурмовому підрозділі",
    link: "https://example.com/sniper",
  },
  {
    id: "rifleman",
    title: "Стрілець",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Виконання бойових завдань",
    link: "https://example.com/rifleman",
  },
  {
    id: "machine_gunner",
    title: "Кулеметник",
    unitId: "assault_company_2",
    unit: "2-га штурмова рота",
    short: "Вогнева підтримка групи",
    link: "https://example.com/machine-gunner",
  },
  {
    id: "grenadier",
    title: "Гранатометник",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Ураження бронетехніки та укріплень",
    link: "https://example.com/grenadier",
  },
  {
    id: "drone_operator",
    title: "Оператор БПЛА",
    unitId: "uav_unit_2",
    unit: "Взвод аеророзвідки",
    short: "Аеророзвідка та коригування",
    link: "https://example.com/drone",
  },
  {
    id: "fpv_operator",
    title: "Оператор FPV",
    unitId: "uav_unit_1",
    unit: "Рота БПЛА",
    short: "Ураження цілей FPV-дронами",
    link: "https://example.com/fpv",
  },
  {
    id: "artillery_spotter",
    title: "Навідник-розвідник",
    unitId: "artillery_battalion",
    unit: "Артилерійський дивізіон",
    short: "Наведення артилерійського вогню",
    link: "https://example.com/spotter",
  },
  {
    id: "artillery_gunner",
    title: "Артилерист",
    unitId: "artillery_battalion",
    unit: "Артилерійський дивізіон",
    short: "Робота з артсистемами",
    link: "https://example.com/artillery",
  },
  {
    id: "tank_driver",
    title: "Механік-водій танка",
    unitId: "tank_company",
    unit: "Танкова рота",
    short: "Керування та обслуговування танка",
    link: "https://example.com/tank-driver",
  },
  {
    id: "apc_driver",
    title: "Механік-водій БМП",
    unitId: "tank_battalion_1",
    unit: "1-й танковий батальйон",
    short: "Управління бойовою машиною",
    link: "https://example.com/apc-driver",
  },
  {
    id: "combat_medic",
    title: "Бойовий медик",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Допомога пораненим на полі бою",
    link: "https://example.com/medic",
  },
  {
    id: "paramedic",
    title: "Медик-евакуатор",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Медична евакуація",
    link: "https://example.com/paramedic",
  },
  {
    id: "radio_operator",
    title: "Радіотелефоніст",
    unitId: "ew_unit",
    unit: "Підрозділ РЕБ",
    short: "Забезпечення звʼязку",
    link: "https://example.com/radio",
  },
  {
    id: "commander_squad",
    title: "Командир відділення",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Управління особовим складом",
    link: "https://example.com/squad-leader",
  },
  {
    id: "engineer_sapper",
    title: "Сапер",
    unitId: "engineering_unit",
    unit: "Інженерно-саперний взвод",
    short: "Мінування та розмінування",
    link: "https://example.com/sapper",
  },
  {
    id: "fortification",
    title: "Інженер-фортифікатор",
    unitId: "engineering_unit",
    unit: "Інженерно-саперний взвод",
    short: "Облаштування позицій",
    link: "https://example.com/fortification",
  },
  {
    id: "logistician",
    title: "Логіст",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Облік та постачання",
    link: "https://example.com/logistics",
  },
  {
    id: "warehouse",
    title: "Комірник",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Облік майна та БК",
    link: "https://example.com/warehouse",
  },
  {
    id: "cook",
    title: "Кухар",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Харчування особового складу",
    link: "https://example.com/cook",
  },
  {
    id: "auto_mechanic",
    title: "Автомеханік",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Ремонт та обслуговування техніки",
    link: "https://example.com/mechanic",
  },
  {
    id: "recon_scout",
    title: "Розвідник",
    unitId: "recon_unit",
    unit: "Розвідувальний взвод",
    short: "Тактична розвідка та спостереження",
    link: "https://example.com/recon",
  },
  {
    id: "recon_commander",
    title: "Командир розвідгрупи",
    unitId: "recon_unit",
    unit: "Розвідувальний взвод",
    short: "Управління розвідувальною групою",
    link: "https://example.com/recon-commander",
  },
  {
    id: "air_defense_operator",
    title: "Оператор ППО",
    unitId: "air_defense_unit",
    unit: "Підрозділ ППО",
    short: "Виявлення та ураження повітряних цілей",
    link: "https://example.com/air-defense",
  },
  {
    id: "manpads_operator",
    title: "Оператор ПЗРК",
    unitId: "air_defense_unit",
    unit: "Підрозділ ППО",
    short: "Переносні зенітні ракетні комплекси",
    link: "https://example.com/manpads",
  },
  {
    id: "fpv_commander",
    title: "Командир екіпажу FPV",
    unitId: "uav_unit_1",
    unit: "Рота БПЛА",
    short: "Планування та координація FPV-ударів",
    link: "https://example.com/fpv-commander",
  },
  {
    id: "uav_technician",
    title: "Технік БПЛА",
    unitId: "uav_unit_1",
    unit: "Рота БПЛА",
    short: "Обслуговування та ремонт дронів",
    link: "https://example.com/uav-tech",
  },
  {
    id: "ew_operator",
    title: "Оператор РЕБ",
    unitId: "ew_unit",
    unit: "Підрозділ РЕБ",
    short: "Придушення та захист радіоканалів",
    link: "https://example.com/ew-operator",
  },
  {
    id: "ew_analyst",
    title: "Аналітик РЕБ",
    unitId: "ew_unit",
    unit: "Підрозділ РЕБ",
    short: "Аналіз радіообстановки",
    link: "https://example.com/ew-analyst",
  },
  {
    id: "artillery_loader",
    title: "Заряджаючий",
    unitId: "artillery_battalion",
    unit: "Артилерійський дивізіон",
    short: "Підготовка та заряджання боєприпасів",
    link: "https://example.com/loader",
  },
  {
    id: "mlrs_operator",
    title: "Оператор РСЗВ",
    unitId: "mlrs_unit",
    unit: "Підрозділ РСЗВ",
    short: "Робота з реактивними системами",
    link: "https://example.com/mlrs",
  },
  {
    id: "tank_commander",
    title: "Командир танка",
    unitId: "tank_company",
    unit: "Танкова рота",
    short: "Управління екіпажем танка",
    link: "https://example.com/tank-commander",
  },
  {
    id: "tank_gunner",
    title: "Навідник танка",
    unitId: "tank_company",
    unit: "Танкова рота",
    short: "Наведення та ведення вогню",
    link: "https://example.com/tank-gunner",
  },
  {
    id: "support_gunner",
    title: "Кулеметник підтримки",
    unitId: "support_platoon",
    unit: "Взвод вогневої підтримки",
    short: "Вогнева підтримка штурмових груп",
    link: "https://example.com/support-gunner",
  },
  {
    id: "mortar_operator",
    title: "Мінометник",
    unitId: "support_platoon",
    unit: "Взвод вогневої підтримки",
    short: "Ведення мінометного вогню",
    link: "https://example.com/mortar",
  },
  {
    id: "driver_supply",
    title: "Водій забезпечення",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Перевезення особового складу та вантажів",
    link: "https://example.com/driver",
  },
  {
    id: "repair_mechanic",
    title: "Механік-ремонтник",
    unitId: "repair_unit",
    unit: "Ремонтний взвод",
    short: "Польовий ремонт техніки",
    link: "https://example.com/repair",
  },
  {
    id: "evacuation_driver",
    title: "Водій евакуації",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Евакуація поранених з поля бою",
    link: "https://example.com/evac-driver",
  },
  {
    id: "medical_instructor",
    title: "Інструктор з такмеду",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Навчання особового складу домедичній допомозі",
    link: "https://example.com/tacmed",
  },
  {
    id: "hq_operator",
    title: "Офіцер штабу",
    unitId: "hq_unit",
    unit: "Штаб підрозділу",
    short: "Планування та координація операцій",
    link: "https://example.com/hq",
  },
  {
    id: "clerk",
    title: "Діловод",
    unitId: "hq_unit",
    unit: "Штаб підрозділу",
    short: "Документообіг та облік особового складу",
    link: "https://example.com/clerk",
  },
];

export const getVacancyById = (id: string) => {
  return vacancies.find((v) => v.id === id);
};
