export const vacancies = [
  {
    id: "sniper",
    title: "Снайпер",
    unit: "3 ОШБ",
    short: "Бойова робота в штурмовому підрозділі",
    link: "https://example.com/sniper",
  },
  {
    id: "rifleman",
    title: "Стрілець",
    unit: "Механізований батальйон",
    short: "Виконання бойових завдань",
    link: "https://example.com/rifleman",
  },
  {
    id: "machine_gunner",
    title: "Кулеметник",
    unit: "Штурмова рота",
    short: "Вогнева підтримка групи",
    link: "https://example.com/machine-gunner",
  },
  {
    id: "grenadier",
    title: "Гранатометник",
    unit: "Піхотна рота",
    short: "Ураження бронетехніки та укріплень",
    link: "https://example.com/grenadier",
  },
  {
    id: "drone_operator",
    title: "Оператор БПЛА",
    unit: "Рота БПЛА",
    short: "Аеророзвідка та коригування",
    link: "https://example.com/drone",
  },
  {
    id: "fpv_operator",
    title: "Оператор FPV",
    unit: "Підрозділ ударних БПЛА",
    short: "Ураження цілей FPV-дронами",
    link: "https://example.com/fpv",
  },
  {
    id: "artillery_spotter",
    title: "Навідник-розвідник",
    unit: "Артдивізіон",
    short: "Наведення артилерійського вогню",
    link: "https://example.com/spotter",
  },
  {
    id: "artillery_gunner",
    title: "Артилерист",
    unit: "Артилерійська батарея",
    short: "Робота з артсистемами",
    link: "https://example.com/artillery",
  },
  {
    id: "tank_driver",
    title: "Механік-водій танка",
    unit: "Танкова рота",
    short: "Керування та обслуговування танка",
    link: "https://example.com/tank-driver",
  },
  {
    id: "apc_driver",
    title: "Механік-водій БМП",
    unit: "Мехбат",
    short: "Управління бойовою машиною",
    link: "https://example.com/apc-driver",
  },
  {
    id: "combat_medic",
    title: "Бойовий медик",
    unit: "Медична рота",
    short: "Допомога пораненим на полі бою",
    link: "https://example.com/medic",
  },
  {
    id: "paramedic",
    title: "Медик-евакуатор",
    unit: "Евакуаційна група",
    short: "Медична евакуація",
    link: "https://example.com/paramedic",
  },
  {
    id: "radio_operator",
    title: "Радіотелефоніст",
    unit: "Штабна рота",
    short: "Забезпечення звʼязку",
    link: "https://example.com/radio",
  },
  {
    id: "commander_squad",
    title: "Командир відділення",
    unit: "Піхотний підрозділ",
    short: "Управління особовим складом",
    link: "https://example.com/squad-leader",
  },
  {
    id: "engineer_sapper",
    title: "Сапер",
    unit: "Інженерний взвод",
    short: "Мінування та розмінування",
    link: "https://example.com/sapper",
  },
  {
    id: "fortification",
    title: "Інженер-фортифікатор",
    unit: "Інженерна рота",
    short: "Облаштування позицій",
    link: "https://example.com/fortification",
  },
  {
    id: "logistician",
    title: "Логіст",
    unit: "Рота забезпечення",
    short: "Облік та постачання",
    link: "https://example.com/logistics",
  },
  {
    id: "warehouse",
    title: "Комірник",
    unit: "Тиловий склад",
    short: "Облік майна та БК",
    link: "https://example.com/warehouse",
  },
  {
    id: "cook",
    title: "Кухар",
    unit: "Польова кухня",
    short: "Харчування особового складу",
    link: "https://example.com/cook",
  },
  {
    id: "auto_mechanic",
    title: "Автомеханік",
    unit: "Ремонтна рота",
    short: "Ремонт та обслуговування техніки",
    link: "https://example.com/mechanic",
  },
];

export const getVacancyById = (id: string) => {
  return vacancies.find((v) => v.id === id);
};
