export const vacancies = [
  {
    id: "sniper",
    title: "Снайпер",
    unitId: "sniper_unit",
    unit: "Снайперська група",
    short: "Бойова робота в штурмовому підрозділі",
    link: "https://example.com/sniper",
  },
  {
    id: "rifleman",
    title: "Стрілець",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Виконання бойових завдань",
    link: "https://example.com/rifleman",
  },
  {
    id: "machine_gunner",
    title: "Кулеметник",
    unitId: "assault_company_2",
    unit: "2-га штурмова рота",
    short: "Вогнева підтримка групи",
    link: "https://example.com/machine-gunner",
  },
  {
    id: "grenadier",
    title: "Гранатометник",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Ураження бронетехніки та укріплень",
    link: "https://example.com/grenadier",
  },
  {
    id: "drone_operator",
    title: "Оператор БПЛА",
    unitId: "uav_unit_2",
    unit: "Взвод аеророзвідки",
    short: "Аеророзвідка та коригування",
    link: "https://example.com/drone",
  },
  {
    id: "fpv_operator",
    title: "Оператор FPV",
    unitId: "uav_unit_1",
    unit: "Рота БПЛА",
    short: "Ураження цілей FPV-дронами",
    link: "https://example.com/fpv",
  },
  {
    id: "artillery_spotter",
    title: "Навідник-розвідник",
    unitId: "artillery_battalion",
    unit: "Артилерійський дивізіон",
    short: "Наведення артилерійського вогню",
    link: "https://example.com/spotter",
  },
  {
    id: "artillery_gunner",
    title: "Артилерист",
    unitId: "artillery_battalion",
    unit: "Артилерійський дивізіон",
    short: "Робота з артсистемами",
    link: "https://example.com/artillery",
  },
  {
    id: "tank_driver",
    title: "Механік-водій танка",
    unitId: "tank_company",
    unit: "Танкова рота",
    short: "Керування та обслуговування танка",
    link: "https://example.com/tank-driver",
  },
  {
    id: "apc_driver",
    title: "Механік-водій БМП",
    unitId: "tank_battalion_1",
    unit: "1-й танковий батальйон",
    short: "Управління бойовою машиною",
    link: "https://example.com/apc-driver",
  },
  {
    id: "combat_medic",
    title: "Бойовий медик",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Допомога пораненим на полі бою",
    link: "https://example.com/medic",
  },
  {
    id: "paramedic",
    title: "Медик-евакуатор",
    unitId: "medical_unit",
    unit: "Медична рота",
    short: "Медична евакуація",
    link: "https://example.com/paramedic",
  },
  {
    id: "radio_operator",
    title: "Радіотелефоніст",
    unitId: "ew_unit",
    unit: "Підрозділ РЕБ",
    short: "Забезпечення звʼязку",
    link: "https://example.com/radio",
  },
  {
    id: "commander_squad",
    title: "Командир відділення",
    unitId: "assault_company_1",
    unit: "1-ша штурмова рота",
    short: "Управління особовим складом",
    link: "https://example.com/squad-leader",
  },
  {
    id: "engineer_sapper",
    title: "Сапер",
    unitId: "engineering_unit",
    unit: "Інженерно-саперний взвод",
    short: "Мінування та розмінування",
    link: "https://example.com/sapper",
  },
  {
    id: "fortification",
    title: "Інженер-фортифікатор",
    unitId: "engineering_unit",
    unit: "Інженерно-саперний взвод",
    short: "Облаштування позицій",
    link: "https://example.com/fortification",
  },
  {
    id: "logistician",
    title: "Логіст",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Облік та постачання",
    link: "https://example.com/logistics",
  },
  {
    id: "warehouse",
    title: "Комірник",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Облік майна та БК",
    link: "https://example.com/warehouse",
  },
  {
    id: "cook",
    title: "Кухар",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Харчування особового складу",
    link: "https://example.com/cook",
  },
  {
    id: "auto_mechanic",
    title: "Автомеханік",
    unitId: "logistics_unit",
    unit: "Рота забезпечення",
    short: "Ремонт та обслуговування техніки",
    link: "https://example.com/mechanic",
  },
];

export const getVacancyById = (id: string) => {
  return vacancies.find((v) => v.id === id);
};
